[workspace]
resolver = "2"
members = [
    "crates/duckdb-motorsport-telemetry",
]

[workspace.package]
version = "0.8.1"
edition = "2021"
rust-version = "1.84"
license = "MIT"
repository = "https://github.com/tobi/duckdb_motorsport_telemetry"

[workspace.dependencies]
motorsport-telemetry-core = { git = "https://github.com/tobi/motorsport-telemetry-rs", rev = "72224ca366f13e97857d7515506e5f52abb9ae39" }
cosworth-telemetry = { git = "https://github.com/tobi/motorsport-telemetry-rs", rev = "72224ca366f13e97857d7515506e5f52abb9ae39" }
aim-telemetry = { git = "https://github.com/tobi/motorsport-telemetry-rs", rev = "72224ca366f13e97857d7515506e5f52abb9ae39" }
motec-telemetry = { git = "https://github.com/tobi/motorsport-telemetry-rs", rev = "72224ca366f13e97857d7515506e5f52abb9ae39" }
racelogic-telemetry = { git = "https://github.com/tobi/motorsport-telemetry-rs", rev = "72224ca366f13e97857d7515506e5f52abb9ae39" }
thiserror = "2"

[profile.release]
lto = "thin"
codegen-units = 1
panic = "abort"
strip = "debuginfo"
